package theebrain;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.SingleGraph;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        rb_x = new javax.swing.JRadioButton();
        tf_race = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_obs = new javax.swing.JTextArea();
        bt_registrar = new javax.swing.JButton();
        jdc_born = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        genero = new javax.swing.ButtonGroup();
        arbol = new javax.swing.JDialog();
        tf_nodo_actual = new javax.swing.JTextField();
        bt_agregar_hijo = new javax.swing.JButton();
        cbx_agregar_hijos = new javax.swing.JComboBox<>();
        bt_cambiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbx_cambio_nodo = new javax.swing.JComboBox<>();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jb_Grafo = new javax.swing.JButton();
        cb_Perfiles_Grafo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        bt_registrar_perfil = new javax.swing.JButton();
        bt_mapa_mental = new javax.swing.JButton();
        bt_crear_arbol = new javax.swing.JButton();
        cbx_perfiles = new javax.swing.JComboBox<>();
        cbx_treehead = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Registro de Perfiles");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Raza");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Observaciones");

        genero.add(rb_m);
        rb_m.setText("M");

        genero.add(rb_f);
        rb_f.setText("F");

        genero.add(rb_x);
        rb_x.setText("?");

        ta_obs.setColumns(20);
        ta_obs.setRows(5);
        jScrollPane1.setViewportView(ta_obs);

        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        jMenuBar2.add(jMenu1);
        jMenuBar2.add(jMenu3);

        registro.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro.getContentPane());
        registro.getContentPane().setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(138, 138, 138))
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_born, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_m)
                                .addGap(12, 12, 12)
                                .addComponent(rb_f)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_x))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_race, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(bt_registrar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdc_born, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_m)
                    .addComponent(rb_f)
                    .addComponent(rb_x))
                .addGap(35, 35, 35)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(bt_registrar)
                .addGap(19, 19, 19))
        );

        tf_nodo_actual.setEnabled(false);

        bt_agregar_hijo.setText("Agregar Hijo:");
        bt_agregar_hijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_hijoMouseClicked(evt);
            }
        });

        bt_cambiar.setText("Cambiar");
        bt_cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cambiarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nodo actual");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Administrador del Arbol");

        jLabel10.setText("Ingrese el nodo al que desea cambiar");

        jLabel11.setText("selecione el perfil que desea como hijo");

        javax.swing.GroupLayout arbolLayout = new javax.swing.GroupLayout(arbol.getContentPane());
        arbol.getContentPane().setLayout(arbolLayout);
        arbolLayout.setHorizontalGroup(
            arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arbolLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nodo_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                        .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addComponent(cbx_cambio_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addComponent(bt_agregar_hijo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbx_agregar_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        arbolLayout.setVerticalGroup(
            arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arbolLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(44, 44, 44)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nodo_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_agregar_hijo)
                    .addComponent(cbx_agregar_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cambiar)
                    .addComponent(cbx_cambio_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jb_Grafo.setText("Ok");

        jLabel12.setText("Perfiles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jb_Grafo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Perfiles_Grafo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Perfiles_Grafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jb_Grafo)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("The eBrain");

        bt_registrar_perfil.setText("Registrar Perfiles");
        bt_registrar_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrar_perfilMouseClicked(evt);
            }
        });

        bt_mapa_mental.setText("Crear Mapas Mental");
        bt_mapa_mental.setEnabled(false);

        bt_crear_arbol.setText("Crear arbol genealogico");
        bt_crear_arbol.setEnabled(false);
        bt_crear_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_arbolMouseClicked(evt);
            }
        });
        bt_crear_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear_arbolActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_treehead, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_mapa_mental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_crear_arbol, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_registrar_perfil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(bt_registrar_perfil)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_treehead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear_arbol))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_mapa_mental)
                    .addComponent(cbx_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrar_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrar_perfilMouseClicked
        this.registro.pack();
        this.registro.setModal(true);
        this.setLocationRelativeTo(this);
        this.registro.setVisible(true);
    }//GEN-LAST:event_bt_registrar_perfilMouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        String genero = "";
        if (rb_m.isSelected()) {
            genero = "Masculino";
        } else if (rb_f.isSelected()) {
            genero = "Femenino";
        } else {
            genero = "Desconocido";
        }
        Perfil nuevo = new Perfil(tf_name.getText(), jdc_born.toString(), genero, tf_race.getText(), ta_obs.getText());
        perfiles.add(nuevo);
        tf_name.setText("");
        tf_race.setText("");
        ta_obs.setText("");
        JOptionPane.showMessageDialog(this, "Perfil registrado exitosamente");
        bt_crear_arbol.setEnabled(true);
        bt_mapa_mental.setEnabled(true);
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cbx_perfiles.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cbx_treehead.getModel();
        modelo1.addElement(nuevo);
        modelo2.addElement(nuevo);

    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_crear_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear_arbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crear_arbolActionPerformed

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_crear_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_arbolMouseClicked
        Perfil head = (Perfil) cbx_treehead.getSelectedItem();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_agregar_hijos.getModel();
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i).getNombre() != head.getNombre()) {
                modelo.addElement(perfiles.get(i));
            }
        }
        cbx_agregar_hijos.setModel(modelo);
        nodo_actual = head;
        tf_nodo_actual.setText(head.getNombre());
        this.graphAdd_Perfil(Arbol);
        Arbol.display();
        this.arbol.pack();
        this.arbol.setModal(true);
        this.setLocationRelativeTo(this);
        this.arbol.setVisible(true);
        
        
    }//GEN-LAST:event_bt_crear_arbolMouseClicked

    private void bt_agregar_hijoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_hijoMouseClicked
        // TODO add your handling code here:
        if (bt_agregar_hijo.isEnabled()) {
            for (int i = 0; i < perfiles.size(); i++) {
                if (perfiles.get(i).getNombre() == nodo_actual.getNombre()) {
                    Perfil hijo = (Perfil) cbx_agregar_hijos.getSelectedItem();
                    perfiles.get(i).getHijos().add(hijo);
                    DefaultComboBoxModel modelo0 = (DefaultComboBoxModel) cbx_cambio_nodo.getModel();
                    modelo0.addElement((Perfil) cbx_agregar_hijos.getSelectedItem());
                    cbx_cambio_nodo.setModel(modelo0);
                    cbx_cambio_nodo.setModel(modelo0);
                    JOptionPane.showMessageDialog(this, tf_nodo_actual.getText() + " se le ha agregado un nuevo hijo");
                }
            }
            System.out.println("------");
            for (int i = 0; i < perfiles.size(); i++) {
                for (int j = 0; j < perfiles.get(i).getHijos().size(); j++) {
                    System.out.println(perfiles.get(i).getNombre() + " " + perfiles.get(i).getHijos().get(j).getNombre());
                }
            }
            System.out.println("------");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_agregar_hijos.getModel();
            modelo.removeElementAt(cbx_agregar_hijos.getSelectedIndex());
            cbx_agregar_hijos.setModel(modelo);
            if (cbx_agregar_hijos.getItemCount() == 0) {
                bt_agregar_hijo.setEnabled(false);
            }
            this.graphAdd_Hijo(Arbol);
        }


    }//GEN-LAST:event_bt_agregar_hijoMouseClicked

    private void bt_cambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cambiarMouseClicked
        // TODO add your handling code here:
        boolean revision = true;
        Perfil nuevo_actual = (Perfil) cbx_cambio_nodo.getSelectedItem();
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i).getNombre() == nuevo_actual.getNombre()) {
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_cambio_nodo.getModel();
                modelo.removeElementAt(cbx_cambio_nodo.getSelectedIndex());
                modelo.addElement(nodo_actual);
                tf_nodo_actual.setText(nuevo_actual.getNombre());
                nodo_actual = nuevo_actual;
                revision = false;
            }
        }
        if (revision) {
            JOptionPane.showMessageDialog(this, "el nombre que usted ha ingresado no exite o no se encuentra en el arbol");
        } else {
            JOptionPane.showMessageDialog(this, "el nodo actual ha Cambiado");
        }
    }//GEN-LAST:event_bt_cambiarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog arbol;
    private javax.swing.JButton bt_agregar_hijo;
    private javax.swing.JButton bt_cambiar;
    private javax.swing.JButton bt_crear_arbol;
    private javax.swing.JButton bt_mapa_mental;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_registrar_perfil;
    private javax.swing.JComboBox<String> cb_Perfiles_Grafo;
    private javax.swing.JComboBox<String> cbx_agregar_hijos;
    private javax.swing.JComboBox<String> cbx_cambio_nodo;
    private javax.swing.JComboBox<String> cbx_perfiles;
    private javax.swing.JComboBox<String> cbx_treehead;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Grafo;
    private com.toedter.calendar.JDateChooser jdc_born;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_x;
    private javax.swing.JDialog registro;
    private javax.swing.JTextArea ta_obs;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nodo_actual;
    private javax.swing.JTextField tf_race;
    // End of variables declaration//GEN-END:variables
ArrayList<Perfil> perfiles = new ArrayList<Perfil>();
Perfil nodo_actual;
Graph Arbol=new SingleGraph("Arbol Genealogico");

public Graph graphAdd_Perfil(Graph grafo){
    for (int i = 0; i < perfiles.size(); i++) {
        try {
            grafo.addNode(perfiles.get(i).getNombre());
        } catch (Exception e) {
        }
    }
    return grafo;
}
public Graph graphAdd_Hijo(Graph grafo){
    
    for (int i = 0; i < perfiles.size(); i++) {
        try {
            for (int j = 0; j < perfiles.get(i).getHijos().size(); j++) {
                grafo.addEdge("0", perfiles.get(i).getNombre(),  perfiles.get(i).getHijos().get(j).getNombre());
            }
        } catch (Exception e) {
        }
    }
    return grafo;
}
}
