package theebrain;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        rb_x = new javax.swing.JRadioButton();
        tf_race = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_obs = new javax.swing.JTextArea();
        bt_registrar = new javax.swing.JButton();
        jdc_born = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        genero = new javax.swing.ButtonGroup();
        arbol = new javax.swing.JDialog();
        tf_nodo_actual = new javax.swing.JTextField();
        bt_agregar_hijo = new javax.swing.JButton();
        cbx_agregar_hijos = new javax.swing.JComboBox<>();
        bt_cambiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbx_cambio_nodo = new javax.swing.JComboBox<>();
        jd_MapaMental = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        tf_Perfil_Seleccionado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_Nombre_MapaMental = new javax.swing.JTextField();
        jb_AgregarBoton = new javax.swing.JButton();
        cb_MapaMentales = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jb_AccesarMapaMental = new javax.swing.JButton();
        jd_MapaMental_Palabras = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        tf_MapaMental = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_Palabra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jb_AgregarPalabra = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cb_Palabras = new javax.swing.JComboBox<>();
        jb_modificarPalabra = new javax.swing.JButton();
        jb_eliminarPalabra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_registrar_perfil = new javax.swing.JButton();
        bt_mapa_mental = new javax.swing.JButton();
        bt_crear_arbol = new javax.swing.JButton();
        cbx_perfiles = new javax.swing.JComboBox<>();
        cbx_treehead = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Registro de Perfiles");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genero");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Raza");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Observaciones");

        genero.add(rb_m);
        rb_m.setText("M");

        genero.add(rb_f);
        rb_f.setText("F");

        genero.add(rb_x);
        rb_x.setText("?");

        ta_obs.setColumns(20);
        ta_obs.setRows(5);
        jScrollPane1.setViewportView(ta_obs);

        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        jMenuBar2.add(jMenu1);
        jMenuBar2.add(jMenu3);

        registro.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro.getContentPane());
        registro.getContentPane().setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(138, 138, 138))
            .addGroup(registroLayout.createSequentialGroup()
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_born, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_m)
                                .addGap(12, 12, 12)
                                .addComponent(rb_f)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_x))
                            .addGroup(registroLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_race, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(bt_registrar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdc_born, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_m)
                    .addComponent(rb_f)
                    .addComponent(rb_x))
                .addGap(35, 35, 35)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(bt_registrar)
                .addGap(19, 19, 19))
        );

        arbol.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                arbolComponentShown(evt);
            }
        });
        arbol.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                arbolWindowClosed(evt);
            }
        });

        tf_nodo_actual.setEnabled(false);
        tf_nodo_actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nodo_actualActionPerformed(evt);
            }
        });

        bt_agregar_hijo.setText("Agregar Hijo:");
        bt_agregar_hijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregar_hijoMouseClicked(evt);
            }
        });
        bt_agregar_hijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_hijoActionPerformed(evt);
            }
        });

        bt_cambiar.setText("Cambiar");
        bt_cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cambiarMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nodo actual");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Administrador del Arbol");

        jLabel10.setText("Ingrese el nodo al que desea cambiar");

        jLabel11.setText("selecione el perfil que desea como hijo");

        cbx_cambio_nodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cambio_nodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout arbolLayout = new javax.swing.GroupLayout(arbol.getContentPane());
        arbol.getContentPane().setLayout(arbolLayout);
        arbolLayout.setHorizontalGroup(
            arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arbolLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nodo_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                        .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addComponent(cbx_cambio_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addComponent(bt_agregar_hijo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbx_agregar_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, arbolLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        arbolLayout.setVerticalGroup(
            arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arbolLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(44, 44, 44)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nodo_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_agregar_hijo)
                    .addComponent(cbx_agregar_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cambiar)
                    .addComponent(cbx_cambio_nodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jLabel12.setText("Perfil Seleccionado:");

        tf_Perfil_Seleccionado.setEnabled(false);

        jLabel13.setText("Ingrese nombre del mapa mental:");

        jb_AgregarBoton.setText("Agregar");
        jb_AgregarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarBotonMouseClicked(evt);
            }
        });

        jLabel14.setText("Mapas Mentales");

        jb_AccesarMapaMental.setText("Accesar");
        jb_AccesarMapaMental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AccesarMapaMentalMouseClicked(evt);
            }
        });
        jb_AccesarMapaMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AccesarMapaMentalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_MapaMentalLayout = new javax.swing.GroupLayout(jd_MapaMental.getContentPane());
        jd_MapaMental.getContentPane().setLayout(jd_MapaMentalLayout);
        jd_MapaMentalLayout.setHorizontalGroup(
            jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MapaMentalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_MapaMentalLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Nombre_MapaMental))
                    .addGroup(jd_MapaMentalLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Perfil_Seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMentalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_AgregarBoton)
                .addGap(250, 250, 250))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMentalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMentalLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_MapaMentales, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMentalLayout.createSequentialGroup()
                        .addComponent(jb_AccesarMapaMental)
                        .addGap(247, 247, 247))))
        );
        jd_MapaMentalLayout.setVerticalGroup(
            jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MapaMentalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_Perfil_Seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_Nombre_MapaMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jb_AgregarBoton)
                .addGap(59, 59, 59)
                .addGroup(jd_MapaMentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_MapaMentales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(33, 33, 33)
                .addComponent(jb_AccesarMapaMental)
                .addGap(26, 26, 26))
        );

        jLabel15.setText("Mapa Mental");

        tf_MapaMental.setEnabled(false);
        tf_MapaMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MapaMentalActionPerformed(evt);
            }
        });

        jLabel16.setText("Ingrese la Palabra:");

        jLabel17.setText("Digite la importanica:");

        jb_AgregarPalabra.setText("Agregar");
        jb_AgregarPalabra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarPalabraMouseClicked(evt);
            }
        });

        jLabel18.setText("Palabras:");

        jb_modificarPalabra.setText("Modificar");
        jb_modificarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarPalabraActionPerformed(evt);
            }
        });

        jb_eliminarPalabra.setText("Eliminar");
        jb_eliminarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarPalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_MapaMental_PalabrasLayout = new javax.swing.GroupLayout(jd_MapaMental_Palabras.getContentPane());
        jd_MapaMental_Palabras.getContentPane().setLayout(jd_MapaMental_PalabrasLayout);
        jd_MapaMental_PalabrasLayout.setHorizontalGroup(
            jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMental_PalabrasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_AgregarPalabra)
                .addGap(192, 192, 192))
            .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                        .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_MapaMental, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_Palabra)))
                            .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_MapaMental_PalabrasLayout.createSequentialGroup()
                        .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_Palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jb_modificarPalabra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addComponent(jb_eliminarPalabra)))
                        .addGap(23, 23, 23))))
        );
        jd_MapaMental_PalabrasLayout.setVerticalGroup(
            jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MapaMental_PalabrasLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_MapaMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jb_AgregarPalabra)
                .addGap(44, 44, 44)
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cb_Palabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jd_MapaMental_PalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificarPalabra)
                    .addComponent(jb_eliminarPalabra))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("The eBrain");

        bt_registrar_perfil.setText("Registrar Perfiles");
        bt_registrar_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrar_perfilMouseClicked(evt);
            }
        });

        bt_mapa_mental.setText("Crear Mapas Mental");
        bt_mapa_mental.setEnabled(false);
        bt_mapa_mental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mapa_mentalMouseClicked(evt);
            }
        });

        bt_crear_arbol.setText("Crear arbol genealogico");
        bt_crear_arbol.setEnabled(false);
        bt_crear_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crear_arbolMouseClicked(evt);
            }
        });
        bt_crear_arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear_arbolActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_treehead, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_mapa_mental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_crear_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_registrar_perfil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(bt_registrar_perfil)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_treehead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear_arbol))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_mapa_mental)
                    .addComponent(cbx_perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrar_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrar_perfilMouseClicked
        this.registro.pack();
        this.registro.setModal(true);
        this.setLocationRelativeTo(this);
        this.registro.setVisible(true);
    }//GEN-LAST:event_bt_registrar_perfilMouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        String genero = "";
        if (rb_m.isSelected()) {
            genero = "Masculino";
        } else if (rb_f.isSelected()) {
            genero = "Femenino";
        } else {
            genero = "Desconocido";
        }
        Perfil nuevo = new Perfil(tf_name.getText(), jdc_born.toString(), genero, tf_race.getText(), ta_obs.getText());
        perfiles.add(nuevo);
        tf_name.setText("");
        tf_race.setText("");
        ta_obs.setText("");
        JOptionPane.showMessageDialog(this, "Perfil registrado exitosamente");
        bt_crear_arbol.setEnabled(true);
        bt_mapa_mental.setEnabled(true);
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cbx_perfiles.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cbx_treehead.getModel();
        modelo1.addElement(nuevo);
        modelo2.addElement(nuevo);

    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_crear_arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear_arbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crear_arbolActionPerformed

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed

    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_crear_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crear_arbolMouseClicked
        System.out.println("Antes------");
        for (int i = 0; i < perfiles.size() ; i++) {
            for (int j = 0; j < perfiles.get(i).getHijos().size(); j++) {
                System.out.println(perfiles.get(i)+"->"+perfiles.get(i).getHijos().get(j));
            }
        }
        System.out.println("Despues------");
        for (int i = 0; i < perfiles.size(); i++) {
            perfiles.get(i).setHijos(new ArrayList<Perfil>());
        }
        for (int i = 0; i < perfiles.size(); i++) {
            for (int j = 0; j < perfiles.get(i).getHijos().size(); j++) {
                System.out.println(perfiles.get(i)+"->"+perfiles.get(i).getHijos().get(j));
            }
        }
        cbx_agregar_hijos.setModel(new DefaultComboBoxModel());
        cbx_cambio_nodo.setModel(new DefaultComboBoxModel());
        Perfil head = (Perfil) cbx_treehead.getSelectedItem();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_agregar_hijos.getModel();
        Arbol = new SingleGraph("Arbol Genealogico");
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i).getNombre() != head.getNombre()) {
                modelo.addElement(perfiles.get(i));
            }
        }
        cbx_agregar_hijos.setModel(modelo);
        nodo_actual = head;
        tf_nodo_actual.setText(head.getNombre());
        if (PadreGrafico == false) {
            String styleSheet = "node {"
                    +       "fill-color: blue;"
                    +"}";
            org.graphstream.graph.Node node = Arbol.addNode(head.getNombre());
            node.addAttribute("ui.label","RAIZ PRINCIPAL-----> " + head.getNombre());
            node.addAttribute("ui.stylesheet", styleSheet);
            PadreGrafico = true;
        }
        
        Padre_Perfil = head;
        graphAdd_Perfil(Arbol);
        
        viewer = Arbol.display();
        viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
        
        this.arbol.pack();
        this.setLocationRelativeTo(this);
        this.arbol.setVisible(true);


    }//GEN-LAST:event_bt_crear_arbolMouseClicked

    private void bt_agregar_hijoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregar_hijoMouseClicked
        // TODO add your handling code here:
        if (cbx_agregar_hijos.getItemCount()!=0) {
            for (int i = 0; i < perfiles.size(); i++) {
                if (perfiles.get(i).getNombre() == nodo_actual.getNombre()) {
                    Perfil Padre = (Perfil) cbx_perfiles.getSelectedItem();
                    Perfil hijo = (Perfil) cbx_agregar_hijos.getSelectedItem();
                    perfiles.get(i).getHijos().add(hijo);
                    DefaultComboBoxModel modelo0 = (DefaultComboBoxModel) cbx_cambio_nodo.getModel();
                    modelo0.addElement((Perfil) cbx_agregar_hijos.getSelectedItem());
                    cbx_cambio_nodo.setModel(modelo0);
                    org.graphstream.graph.Node node = Arbol.getNode(hijo.getNombre());
                    node.addAttribute("ui.label","Hijo de: " + Padre_Perfil.getNombre() + "------>" + node.getId());
                    Arbol.addEdge(contador + "", perfiles.get(i).getNombre(), hijo.getNombre());
                    JOptionPane.showMessageDialog(this, tf_nodo_actual.getText() + " se le ha agregado un nuevo hijo");
                }
            }
            System.out.println("------");
            for (int i = 0; i < perfiles.size(); i++) {
                for (int j = 0; j < perfiles.get(i).getHijos().size(); j++) {
                    System.out.println(perfiles.get(i).getNombre() + " " + perfiles.get(i).getHijos().get(j).getNombre());
                }
            }
            System.out.println("------");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_agregar_hijos.getModel();
            modelo.removeElementAt(cbx_agregar_hijos.getSelectedIndex());
            cbx_agregar_hijos.setModel(modelo);
            contador++;
        }
    }//GEN-LAST:event_bt_agregar_hijoMouseClicked

    private void bt_cambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cambiarMouseClicked
        // TODO add your handling code here:
        boolean revision = true;
        Perfil nuevo_actual = (Perfil) cbx_cambio_nodo.getSelectedItem();
        for (int i = 0; i < perfiles.size(); i++) {
            if (perfiles.get(i).getNombre() == nuevo_actual.getNombre()) {
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbx_cambio_nodo.getModel();
                modelo.removeElementAt(cbx_cambio_nodo.getSelectedIndex());
                modelo.addElement(nodo_actual);
                tf_nodo_actual.setText(nuevo_actual.getNombre());
                nodo_actual = nuevo_actual;
                revision = false;
            }
        }
        if (revision) {
            JOptionPane.showMessageDialog(this, "el nombre que usted ha ingresado no exite o no se encuentra en el arbol");
        } else {
            JOptionPane.showMessageDialog(this, "el nodo actual ha Cambiado");
            Padre_Perfil = nodo_actual;
        }
        
    }//GEN-LAST:event_bt_cambiarMouseClicked

    private void arbolComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_arbolComponentShown

    }//GEN-LAST:event_arbolComponentShown

    private void arbolWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_arbolWindowClosed

    }//GEN-LAST:event_arbolWindowClosed

    private void bt_mapa_mentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mapa_mentalMouseClicked
    MainMapaMental = (Perfil) cbx_perfiles.getSelectedItem();
    
    tf_Perfil_Seleccionado.setText(MainMapaMental.getNombre());
    
    jd_MapaMental.pack();
    jd_MapaMental.setLocationRelativeTo(this);
    jd_MapaMental.setVisible(true);
    
    }//GEN-LAST:event_bt_mapa_mentalMouseClicked

    private void tf_nodo_actualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nodo_actualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nodo_actualActionPerformed

    private void bt_agregar_hijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_hijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregar_hijoActionPerformed

    private void cbx_cambio_nodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cambio_nodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cambio_nodoActionPerformed

    private void jb_AgregarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarBotonMouseClicked
    
    int IndexMain = perfiles.indexOf(MainMapaMental);
    
    MainMapaMental = perfiles.get(IndexMain);
    
    MapaMental Mapa = new MapaMental(new SingleGraph(tf_Nombre_MapaMental.getText()));
    
    DefaultComboBoxModel model = (DefaultComboBoxModel) cb_MapaMentales.getModel();
    
    model.addElement(Mapa.getGrafo().getId());
    
    cb_MapaMentales.setModel(model);
    
    MainMapaMental.getMapas().add(Mapa);
    
    JOptionPane.showConfirmDialog(this, "Se a creado un nuevo mapa mental!");
    
    }//GEN-LAST:event_jb_AgregarBotonMouseClicked

    private void jb_AccesarMapaMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AccesarMapaMentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_AccesarMapaMentalActionPerformed

    private void jb_AccesarMapaMentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AccesarMapaMentalMouseClicked
        
        tf_MapaMental.setText(MainMapaMental.getNombre());
        
        jd_MapaMental_Palabras.setLocationRelativeTo(this);
        jd_MapaMental_Palabras.pack();
        jd_MapaMental_Palabras.setVisible(true);
        
    }//GEN-LAST:event_jb_AccesarMapaMentalMouseClicked

    private void tf_MapaMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MapaMentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MapaMentalActionPerformed

    private void jb_AgregarPalabraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarPalabraMouseClicked
        
        
        
    }//GEN-LAST:event_jb_AgregarPalabraMouseClicked

    private void jb_eliminarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_eliminarPalabraActionPerformed

    private void jb_modificarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_modificarPalabraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog arbol;
    private javax.swing.JButton bt_agregar_hijo;
    private javax.swing.JButton bt_cambiar;
    private javax.swing.JButton bt_crear_arbol;
    private javax.swing.JButton bt_mapa_mental;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_registrar_perfil;
    private javax.swing.JComboBox<String> cb_MapaMentales;
    private javax.swing.JComboBox<String> cb_Palabras;
    private javax.swing.JComboBox<String> cbx_agregar_hijos;
    private javax.swing.JComboBox<String> cbx_cambio_nodo;
    private javax.swing.JComboBox<String> cbx_perfiles;
    private javax.swing.JComboBox<String> cbx_treehead;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton jb_AccesarMapaMental;
    private javax.swing.JButton jb_AgregarBoton;
    private javax.swing.JButton jb_AgregarPalabra;
    private javax.swing.JButton jb_eliminarPalabra;
    private javax.swing.JButton jb_modificarPalabra;
    private javax.swing.JDialog jd_MapaMental;
    private javax.swing.JDialog jd_MapaMental_Palabras;
    private com.toedter.calendar.JDateChooser jdc_born;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_x;
    private javax.swing.JDialog registro;
    private javax.swing.JTextArea ta_obs;
    private javax.swing.JTextField tf_MapaMental;
    private javax.swing.JTextField tf_Nombre_MapaMental;
    private javax.swing.JTextField tf_Palabra;
    private javax.swing.JTextField tf_Perfil_Seleccionado;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nodo_actual;
    private javax.swing.JTextField tf_race;
    // End of variables declaration//GEN-END:variables
ArrayList<Perfil> perfiles = new ArrayList<Perfil>();
    Perfil nodo_actual;
    Graph Arbol = new SingleGraph("Arbol Genealogico");
    int contador = 0;
    boolean PadreGrafico = false;
    Perfil Padre_Perfil;
    Viewer viewer;
    Perfil MainMapaMental;
    
    public Graph graphAdd_Perfil(Graph grafo) {
        for (int i = 0; i < perfiles.size(); i++) {
            try {
                if (i == 0) {
                } else {
                    org.graphstream.graph.Node node = grafo.addNode(perfiles.get(i).getNombre());
                }
            } catch (Exception e) {
            }
        }
        return grafo;
    }
}
